package no.uib.fragmentation_analyzer.gui;

/**
 * A simple dialog for selecting the label type to use for the plot.
 *
 * @author Harald Barsnes
 */
public class PlotLabelSelection extends javax.swing.JDialog {

    private FragmentationAnalyzer fragmentationAnalyzer;

    /** 
     * Creates a new PlotLabelSelection dialog and makes it visible.
     */
    public PlotLabelSelection(FragmentationAnalyzer fragmentationAnalyzer, boolean modal, boolean enableFragmentIonScoringType) {
        super(fragmentationAnalyzer, modal);

        this.fragmentationAnalyzer = fragmentationAnalyzer;

        initComponents();

        fragmentIonScoringTypeJRadioButton.setEnabled(enableFragmentIonScoringType);

        // set the current label type
        if(fragmentationAnalyzer.getLabelType() == fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_INSTRUMENT){
            instrumentNameJRadioButton.setSelected(true);
        } else if(fragmentationAnalyzer.getLabelType() == fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_FRAGMENT_ION_TYPE){
            fragmentIonTypeJRadioButton.setSelected(true);
        } else if(fragmentationAnalyzer.getLabelType() == fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_FRAGMENT_ION_SCORING_TYPE){
            fragmentIonScoringTypeJRadioButton.setSelected(true);
        }

        setLocationRelativeTo(fragmentationAnalyzer);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        okJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        instrumentNameJRadioButton = new javax.swing.JRadioButton();
        fragmentIonTypeJRadioButton = new javax.swing.JRadioButton();
        fragmentIonScoringTypeJRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select the Data Point Label");
        setResizable(false);

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        buttonGroup.add(instrumentNameJRadioButton);
        instrumentNameJRadioButton.setText("Instrument Name");
        instrumentNameJRadioButton.setToolTipText("<html>\nUse the instrument name as the data<br>\npoint label and and coloring scheme\n</html>");
        instrumentNameJRadioButton.setIconTextGap(15);

        buttonGroup.add(fragmentIonTypeJRadioButton);
        fragmentIonTypeJRadioButton.setText("Fragment Ion Type");
        fragmentIonTypeJRadioButton.setToolTipText("<html>\nUse the fragment ion type as the data<br>\npoint label and coloring scheme.\n</html>");
        fragmentIonTypeJRadioButton.setIconTextGap(15);

        buttonGroup.add(fragmentIonScoringTypeJRadioButton);
        fragmentIonScoringTypeJRadioButton.setText("Fragment Ion Scoring Type");
        fragmentIonScoringTypeJRadioButton.setToolTipText("<html>\nUse the fragment ion scoring type as the data<br>\npoint label and coloring scheme.\n</html>");
        fragmentIonScoringTypeJRadioButton.setIconTextGap(15);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fragmentIonScoringTypeJRadioButton)
                    .add(fragmentIonTypeJRadioButton)
                    .add(instrumentNameJRadioButton))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(instrumentNameJRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fragmentIonTypeJRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fragmentIonScoringTypeJRadioButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(okJButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelJButton)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelJButton, okJButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okJButton)
                    .add(cancelJButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog.
     *
     * @param evt
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        fragmentationAnalyzer.cancelProgress();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Sends the label type selection to the FragmentationAnalyzer and
     * then closes the dialog.
     *
     * @param evt
     */
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed

        if(instrumentNameJRadioButton.isSelected()){
            fragmentationAnalyzer.setLabelType(fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_INSTRUMENT);
        } else if(fragmentIonTypeJRadioButton.isSelected()){
            fragmentationAnalyzer.setLabelType(fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_FRAGMENT_ION_TYPE);
        } else if(fragmentIonScoringTypeJRadioButton.isSelected()){
            fragmentationAnalyzer.setLabelType(fragmentationAnalyzer.getProperties().PLOT_LABEL_TYPE_FRAGMENT_ION_SCORING_TYPE);
        }

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JRadioButton fragmentIonScoringTypeJRadioButton;
    private javax.swing.JRadioButton fragmentIonTypeJRadioButton;
    private javax.swing.JRadioButton instrumentNameJRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okJButton;
    // End of variables declaration//GEN-END:variables
}
