package no.uib.fragmentation_analyzer.gui;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import no.uib.fragmentation_analyzer.util.Properties;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.plot.Marker;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.ui.Layer;

/**
 * A dialog for selecting the currently visible data series in a mass error plot.
 *
 * @author Harald Barsnes
 */
public class MassErrorDataSeriesSelection extends javax.swing.JDialog {

    private ChartPanel chartPanel;
    private HashMap<String, Integer> seriesKeyToSeriesNumber;
    private boolean selectAllSeries = true;

    /**
     * Creates a new MassErrorDataSeriesSelection dialog and makes it visible
     *
     * @param fragmentationAnalyzer
     * @param chartPanel
     * @param modal
     */
    public MassErrorDataSeriesSelection(FragmentationAnalyzer fragmentationAnalyzer, boolean modal, ChartPanel chartPanel) {
        super(fragmentationAnalyzer, modal);
        initComponents();

        this.chartPanel = chartPanel;

        insertDataSeries();

        // set the column properties
        dataSeriesJXTable.getColumn(" ").setMinWidth(30);
        dataSeriesJXTable.getColumn(" ").setMaxWidth(30);
        dataSeriesJXTable.getColumn("  ").setMaxWidth(30);
        dataSeriesJXTable.getColumn("  ").setMinWidth(30);

        setLocationRelativeTo(fragmentationAnalyzer);
        setVisible(true);
    }

    /**
     * Inserts the data about the data series into the table.
     */
    private void insertDataSeries() {
        XYDataset xyDataSet = ((XYPlot) chartPanel.getChart().getPlot()).getDataset(0);

        ArrayList<String> seriesKeys = new ArrayList<String>();
        seriesKeyToSeriesNumber = new HashMap<String, Integer>();

        // get all the data series keys
        for (int i = 0; i < xyDataSet.getSeriesCount(); i++) {
            seriesKeys.add(xyDataSet.getSeriesKey(i).toString());
            seriesKeyToSeriesNumber.put(xyDataSet.getSeriesKey(i).toString(), i);
        }

        // sort the series keys in acending order
        java.util.Collections.sort(seriesKeys);

        // add the series keys to the table
        for (int i = 0; i < seriesKeys.size(); i++) {
            ((DefaultTableModel) dataSeriesJXTable.getModel()).addRow(new Object[]{
                        new Integer((i + 1)), seriesKeys.get(i),
                        ((XYPlot) chartPanel.getChart().getPlot()).getRenderer(0).isSeriesVisible(
                        seriesKeyToSeriesNumber.get(seriesKeys.get(i)))
                    });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectSeriesJPopupMenu = new javax.swing.JPopupMenu();
        selectAllSeriesJMenuItem = new javax.swing.JMenuItem();
        invertSelectionJMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataSeriesJXTable = new org.jdesktop.swingx.JXTable();
        okJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        selectAllSeriesJMenuItem.setText("Select/Deselect All");
        selectAllSeriesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllSeriesJMenuItemActionPerformed(evt);
            }
        });
        selectSeriesJPopupMenu.add(selectAllSeriesJMenuItem);

        invertSelectionJMenuItem.setText("Invert Selection");
        invertSelectionJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertSelectionJMenuItemActionPerformed(evt);
            }
        });
        selectSeriesJPopupMenu.add(invertSelectionJMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Series Selection");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Series", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        dataSeriesJXTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ", "Series Name", "  "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataSeriesJXTable.setOpaque(false);
        dataSeriesJXTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dataSeriesJXTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(dataSeriesJXTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDialogJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelJButton, okJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(okJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updated the visible series selection in the plot and then
     * closes the dialog.
     *
     * @param evt
     */
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed

        // get the markers
        Collection tempMarkers = ((XYPlot) chartPanel.getChart().getPlot()).getDomainMarkers(Layer.BACKGROUND);

        HashMap<String, Marker> markers = new HashMap<String, Marker>();

        if (tempMarkers != null) {
            Iterator markerIterator = tempMarkers.iterator();

            while (markerIterator.hasNext()) {
                Marker currentMarker = ((Marker) markerIterator.next());
                markers.put(currentMarker.getLabel(), currentMarker);
            }
        }

        // read the contents of the table and update the data series selection
        for (int i = 0; i < dataSeriesJXTable.getRowCount(); i++) {

            String currentSeriesKey = (String) dataSeriesJXTable.getValueAt(i, 1);
            boolean isCurrentlySelected = ((Boolean) dataSeriesJXTable.getValueAt(i, 2)).booleanValue();

            // update the data series selection
            ((XYPlot) chartPanel.getChart().getPlot()).getRenderer(0).setSeriesVisible(
                    seriesKeyToSeriesNumber.get(currentSeriesKey), isCurrentlySelected);

            // update the marker
            if (markers.get(currentSeriesKey) != null) {
                if (isCurrentlySelected) {
                    markers.get(currentSeriesKey).setAlpha(Properties.DEFAULT_VISIBLE_MARKER_ALPHA);
                } else {
                    markers.get(currentSeriesKey).setAlpha(Properties.DEFAULT_NON_VISIBLE_MARKER_ALPHA);
                }
            }
        }

        closeDialogJButtonActionPerformed(null);

    }//GEN-LAST:event_okJButtonActionPerformed

    /**
     * Closes the dialog.
     *
     * @param evt
     */
    private void closeDialogJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDialogJButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_closeDialogJButtonActionPerformed

    /**
     * Opens the data series selection popup menu if a right click in the
     * table is detected.
     *
     * @param evt
     */
    private void dataSeriesJXTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataSeriesJXTableMouseReleased

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
            selectSeriesJPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_dataSeriesJXTableMouseReleased

    /**
     * Selects or deselects all the data series.
     *
     * @param evt
     */
    private void selectAllSeriesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllSeriesJMenuItemActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        if (selectAllSeries) {
            for (int i = 0; i < dataSeriesJXTable.getRowCount(); i++) {
                dataSeriesJXTable.setValueAt(new Boolean(true), i, dataSeriesJXTable.getColumnCount() - 1);
            }
        } else {
            for (int i = 0; i < dataSeriesJXTable.getRowCount(); i++) {
                if ((((Boolean) dataSeriesJXTable.getValueAt(i, dataSeriesJXTable.getColumnCount() - 1)).booleanValue())) {
                    dataSeriesJXTable.setValueAt(new Boolean(false), i, dataSeriesJXTable.getColumnCount() - 1);
                }
            }
        }

        selectAllSeries = !selectAllSeries;

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_selectAllSeriesJMenuItemActionPerformed

    /**
     * Inverts the current data series selection.
     *
     * @param evt
     */
    private void invertSelectionJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertSelectionJMenuItemActionPerformed
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        selectAllSeries = true;

        for (int i = 0; i < dataSeriesJXTable.getRowCount(); i++) {
            dataSeriesJXTable.setValueAt(
                    new Boolean(!((Boolean) dataSeriesJXTable.getValueAt(
                    i, dataSeriesJXTable.getColumnCount() - 1)).booleanValue()),
                    i, dataSeriesJXTable.getColumnCount() - 1);
        }

        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
}//GEN-LAST:event_invertSelectionJMenuItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private org.jdesktop.swingx.JXTable dataSeriesJXTable;
    private javax.swing.JMenuItem invertSelectionJMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okJButton;
    private javax.swing.JMenuItem selectAllSeriesJMenuItem;
    private javax.swing.JPopupMenu selectSeriesJPopupMenu;
    // End of variables declaration//GEN-END:variables
}
